name        = "Ergoa-L Mac"
name8       = "ergoal-mac"
locale      = "fr"
variant     = "ergoal-mac"
description = "French (Ergoa-L) mac"
author      = "standousset"
url         = "https://github.com/standousset/ergoal"
geometry    = "ERGO"
version     = "1.0.2"

base = '''
╭╌╌╌╌╌┰─────┬─────┬─────┬─────┬─────┰─────┬─────┬─────┬─────┬─────┰╌╌╌╌╌┬╌╌╌╌╌╮
┆ \   ┃     │     │     │     │     ┃     │     │     │     │     ┃     ┆     ┆
┆ /   ┃ 1   │ 2   │ 3   │ 4   │ 5   ┃ 6   │ 7   │ 8   │ 9   │ 0   ┃     ┆     ┆
╰╌╌╌╌╌╂─────┼─────┼─────┼─────┼─────╂─────┼─────┼─────┼─────┼─────╂╌╌╌╌╌┼╌╌╌╌╌┤
·     ┃ Q   │ C   │ O   │ P   │ W ‰ ┃ J “ │ M ” │ D ) │ ! ¡ │ Y   ┃     ┆     ┆
·     ┃   â │   ç │   œ │   ô │   % ┃   « │   » │   ( │***¨ │   û ┃     ┆     ┆
·     ┠─────┼─────┼─────┼─────┼─────╂─────┼─────┼─────┼─────┼─────╂╌╌╌╌╌┼╌╌╌╌╌┤
·     ┃ A   │ S   │ E   │ N   │ F © ┃ L ' │ R   │ T   │ I   │ U   ┃     ┆     ┆
·     ┃   à │   é │   è │   ê │   @ ┃   " │   # │   î │   ï │   ù ┃     ┆     ┆
╭╌╌╌╌╌╂─────┼─────┼─────┼─────┼─────╂─────┼─────┼─────┼─────┼─────╂╌╌╌╌╌┴╌╌╌╌╌╯
┆     ┃ Z   │ X _ │ ? — │ V € │ B ← ┃ :   │ H | │ G   │ ; • │ K ⇄ ┃           ·
┆     ┃   æ │   + │ - – │   $ │   → ┃ . … │   & │  *µ │ , · │   ⤷ ┃           ·
╰╌╌╌╌╌┸─────┴─────┴─────┴─────┴─────┸─────┴─────┴─────┴─────┴─────┚ · · · · · ·
'''

altgr = '''
╭╌╌╌╌╌┰─────┬─────┬─────┬─────┬─────┰─────┬─────┬─────┬─────┬─────┰╌╌╌╌╌┬╌╌╌╌╌╮
┆     ┃   ¹ │   ² │   ³ │   ⁴ │   ⁵ ┃   ⁶ │   ⁷ │   ⁸ │   ⁹ │   ⁰ ┃     ┆     ┆
┆     ┃   ₁ │   ₂ │   ₃ │   ₄ │   ₅ ┃   ₆ │   ₇ │   ₈ │   ₉ │   ₀ ┃     ┆     ┆
╰╌╌╌╌╌╂─────┼─────┼─────┼─────┼─────╂─────┼─────┼─────┼─────┼─────╂╌╌╌╌╌┼╌╌╌╌╌┤
·     ┃     │   ≤ │   ≥ │     │     ┃     │     │   × │     │     ┃     ┆     ┆
·     ┃   ^ │   < │   > │     │     ┃     │   ` │   * │     │   ¥ ┃     ┆     ┆
·     ┠─────┼─────┼─────┼─────┼─────╂─────┼─────┼─────┼─────┼─────╂╌╌╌╌╌┼╌╌╌╌╌┤
·     ┃     │     │     │     │   ≠ ┃     │   ± │     │   ÷ │     ┃     ┆     ┆
·     ┃   { │   ( │   ) │   } │   = ┃   \ │   + │   - │   / │   £ ┃     ┆     ┆
╭╌╌╌╌╌╂─────┼─────┼─────┼─────┼─────╂─────┼─────┼─────┼─────┼─────╂╌╌╌╌╌┴╌╌╌╌╌╯
┆     ┃   ≈ │     │     │     │     ┃     │     │     │     │     ┃           ·
┆     ┃   ~ │   [ │   ] │   ¢ │     ┃     │     │     │     │     ┃           ·
╰╌╌╌╌╌┸─────┴─────┴─────┴─────┴─────┸─────┴─────┴─────┴─────┴─────┚ · · · · · ·
'''

[spacebar]
shift       = "\u0020"  # SPACE
altgr       = "\u202f"  # NARROW NO-BREAK SPACE
altgr_shift = "\u00a0"  # NO-BREAK SPACE
1dk         = "\u2019"  # RIGHT SINGLE QUOTATION MARK
1dk_shift   = "\u2019"  # RIGHT SINGLE QUOTATION MARK


